openapi: 3.0.0
info:
  title: Heyteam API
  description: "This is the (public) documentation for the Heyteam API. The documentation\
    \ contains all the necessary methods to receive, create or modify data related\
    \ to an user and their requirements. The `X-API-KEY` must be included as a header\
    \ in every request made. \n"
  contact:
    email: support@heyteam.com
  version: 1.3.2
servers:
- url: /
tags:
- name: user
  description: Operations about user
paths:
  /users:
    get:
      tags:
      - Users
      summary: List and search users
      description: List and search users
      parameters:
      - name: per_page
        in: query
        description: Number of results per page ("default:20, maximum:100")
        required: false
        style: form
        explode: true
        schema:
          maximum: 100
          type: integer
          default: 20
      - name: client_user_id
        in: query
        description: Search users by client_user_id (external client id)
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: "123"
      - name: id
        in: query
        description: Search users by id (internal heyteam id)
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: "321"
      - name: professional_email
        in: query
        description: Search users by professional_email
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: john.doe@example.com
      - name: firstname
        in: query
        description: Search users by firstname
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: John
      - name: lastname
        in: query
        description: Search users by lastname
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: Doe
      - name: last_update
        in: query
        description: Search users by last update (Europe/Paris timeone)
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: 2020-12-31 12:00:00
      responses:
        "200":
          description: successful operation
          headers:
            X-RateLimit-Remaining:
              style: simple
              explode: false
              schema:
                type: integer
                description: The number of requests left for the 15 minute window
                format: int32
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad Request
          headers:
            X-RateLimit-Remaining:
              style: simple
              explode: false
              schema:
                type: integer
                description: The number of requests left for the 15 minute window
                format: int32
          content:
            application/json:
              schema:
                $ref: '#/definitions/BadRequest'
      security:
      - ApiKeyAuth: []
    post:
      tags:
      - Users
      summary: Create user
      description: Create a basic user on heyteam (not an onboardee)
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserToUpdate'
        required: true
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: Bad Request
          headers:
            X-RateLimit-Remaining:
              style: simple
              explode: false
              schema:
                type: integer
                description: The number of requests left for the 15 minute window
                format: int32
          content:
            application/json:
              schema:
                $ref: '#/definitions/BadRequest'
      security:
      - ApiKeyAuth: []
  /users/{id}:
    get:
      tags:
      - Users
      summary: Get user by id
      parameters:
      - name: id
        in: path
        description: The id that needs to be fetched.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: Bad Request
          headers:
            X-RateLimit-Remaining:
              style: simple
              explode: false
              schema:
                type: integer
                description: The number of requests left for the 15 minute window
                format: int32
          content:
            application/json:
              schema:
                $ref: '#/definitions/BadRequest'
        "404":
          description: User not found
      security:
      - ApiKeyAuth: []
    put:
      tags:
      - Users
      summary: Update user by id
      parameters:
      - name: id
        in: path
        description: id that need to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Update of user object
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UserToUpdate'
        required: true
      responses:
        "200":
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: Bad Request
          headers:
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
          content:
            application/json:
              schema:
                $ref: '#/definitions/BadRequest'
        "404":
          description: User not found
      security:
      - ApiKeyAuth: []
    delete:
      tags:
      - Users
      summary: Delete user by id
      parameters:
      - name: id
        in: path
        description: The user ident that needs to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
        "400":
          description: Bad Request
          headers:
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
          content:
            application/json:
              schema:
                $ref: '#/definitions/BadRequest'
        "404":
          description: User not found
      security:
      - ApiKeyAuth: []
  /users/bulk:
    post:
      tags:
      - Users (bulk mode)
      summary: Creates users with given input array
      requestBody:
        description: List of user object
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UserToUpdate'
        required: true
      responses:
        "201":
          description: Users created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_1'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/definitions/BadRequest'
        "409":
          description: 'Conflict : all the users have not been created'
          headers:
            X-RateLimit-Remaining:
              style: simple
              explode: false
              schema:
                type: integer
                description: The number of requests left for the 15 minute window
                format: int32
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_409'
      security:
      - ApiKeyAuth: []
  /users/{id}/requirements:
    get:
      tags:
      - User requirements
      summary: List and search user's requirement
      parameters:
      - name: id
        in: path
        description: user id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: per_page
        in: query
        description: Number of results per page ("default:20, maximum:100")
        required: false
        style: form
        explode: true
        schema:
          maximum: 100
          type: integer
          default: 20
      - name: client_user_id
        in: query
        description: Search user's requirements by client_user_id (external client
          id)
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: id
        in: query
        description: Search user's requirements by id (internal heyteam id)
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: professional_email
        in: query
        description: Search user's requirements by professional_email
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: name
        in: query
        description: Search user's requirements by name
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          headers:
            X-RateLimit-Remaining:
              style: simple
              explode: false
              schema:
                type: integer
                description: The number of requests left for the 15 minute window
                format: int32
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "400":
          description: Bad Request
          headers:
            X-RateLimit-Remaining:
              style: simple
              explode: false
              schema:
                type: integer
                description: The number of requests left for the 15 minute window
                format: int32
          content:
            application/json:
              schema:
                $ref: '#/definitions/BadRequest'
      security:
      - ApiKeyAuth: []
  /requirements:
    get:
      tags:
      - Requirements
      summary: List and search user's requirements
      parameters:
      - name: per_page
        in: query
        description: Number of results per page ("default:20, maximum:100")
        required: false
        style: form
        explode: true
        schema:
          maximum: 100
          type: integer
          default: 20
      - name: client_user_id
        in: query
        description: Search user's requirements by client_user_id (external client
          id)
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: "123"
      - name: id
        in: query
        description: Search user's requirements by id (internal heyteam id)
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: "321"
      - name: professional_email
        in: query
        description: Search user's requirements by professional_email
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: john.doe@example.com
      - name: name
        in: query
        description: Search user's requirements by name
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: John Doe
      responses:
        "200":
          description: successful operation
          headers:
            X-RateLimit-Remaining:
              style: simple
              explode: false
              schema:
                type: integer
                description: The number of requests left for the 15 minute window
                format: int32
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        "400":
          description: Bad Request
          headers:
            X-RateLimit-Remaining:
              style: simple
              explode: false
              schema:
                type: integer
                description: The number of requests left for the 15 minute window
                format: int32
          content:
            application/json:
              schema:
                $ref: '#/definitions/BadRequest'
      security:
      - ApiKeyAuth: []
  /requirements/{id}:
    get:
      tags:
      - Requirements
      summary: Get user requirement by requirement id
      parameters:
      - name: id
        in: path
        description: The id that needs to be fetched.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Requirement'
        "400":
          description: Bad Request
          headers:
            X-RateLimit-Remaining:
              style: simple
              explode: false
              schema:
                $ref: '#/definitions/BadRequest'
          content:
            application/json:
              schema:
                $ref: '#/definitions/BadRequest'
        "404":
          description: Requirement not found
      security:
      - ApiKeyAuth: []
    delete:
      tags:
      - Requirements
      summary: Delete user's requirement
      parameters:
      - name: id
        in: path
        description: The requirement id that needs to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
        "400":
          description: Bad Request
          headers:
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
          content:
            application/json:
              schema:
                $ref: '#/definitions/BadRequest'
        "404":
          description: Requirement not found
      security:
      - ApiKeyAuth: []
components:
  schemas:
    Requirement:
      properties:
        id:
          type: integer
          description: Primary id
        name:
          type: string
          description: Name of the requirement
        value:
          type: string
        type:
          type: string
          description: Type of the requirement - File is a link to the document
          enum:
          - text
          - file
    User:
      allOf:
      - type: object
        properties:
          id:
            type: integer
            description: Primary id
            example: 321
      - $ref: '#/components/schemas/UserToUpdate'
      - type: object
        properties:
          personal_email:
            maximum: 128
            type: string
            description: Personal email address
            format: email
          status:
            type: string
            enum:
            - draft
            - invited
            - cancelled
            - active
            - inactive
    UserToUpdate:
      required:
      - email
      - firstname
      - lastname
      - professional_email
      type: object
      properties:
        client_user_id:
          maximum: 255
          type: string
          description: Client user ident
          example: "123"
        email:
          maximum: 255
          type: string
          description: ident used for login
          format: email
        gender:
          type: string
          enum:
          - male
          - female
        firstname:
          maximum: 64
          type: string
          example: John
        lastname:
          maximum: 64
          type: string
          example: Doe
        professional_email:
          maximum: 128
          type: string
          description: ident used for email notifications
          format: email
          example: john.doe@example.com
        phone_country_code:
          maximum: 10
          type: number
          example: 33
        phone_number:
          maximum: 20
          type: string
          example: "648090000"
        date_of_birth:
          type: string
          format: date
    inline_response_200:
      type: object
      properties:
        original_query:
          $ref: '#/components/schemas/inline_response_200_original_query'
        data:
          type: array
          description: List of users
          items:
            $ref: '#/components/schemas/User'
        links:
          $ref: '#/components/schemas/inline_response_200_links'
        meta:
          $ref: '#/components/schemas/inline_response_200_meta'
    inline_response_201:
      properties:
        data:
          $ref: '#/components/schemas/User'
    inline_response_201_1:
      properties:
        data:
          type: array
          example:
          - id: 10
            client_user_id: 20
          - id: 21
            client_user_id: 31
          items:
            $ref: '#/components/schemas/inline_response_201_1_data'
    inline_response_409:
      properties:
        data:
          $ref: '#/components/schemas/inline_response_409_data'
    inline_response_200_1:
      properties:
        data:
          type: array
          example:
          - id: 28
            name: Requirement 1
            value: Value 1
          - id: 29
            name: Requirement 2
            value: Value 2
          items:
            $ref: '#/components/schemas/Requirement'
    inline_response_200_2:
      type: object
      properties:
        original_query:
          $ref: '#/components/schemas/inline_response_200_2_original_query'
        data:
          type: array
          description: List of requirements
          items:
            $ref: '#/components/schemas/inline_response_200_2_data'
        links:
          $ref: '#/components/schemas/inline_response_200_2_links'
        meta:
          $ref: '#/components/schemas/inline_response_200_2_meta'
    inline_response_200_original_query:
      type: object
      properties:
        client_user_id:
          type: string
          example: "123"
        id:
          type: string
          example: "321"
        professional_email:
          type: string
          example: john.doe@example.com
        firstname:
          type: string
          example: John
        lastname:
          type: string
          example: Doe
        last_update:
          type: string
          format: date-time
    inline_response_200_links:
      type: object
      properties:
        first:
          type: string
          description: First page url
          example: https://heyteam/api/users?page=1&...
        last:
          type: string
          description: Last page url
          example: https://heyteam/api/users?page=4&...
        prev:
          type: string
          description: Previous page url
          example: https://heyteam/api/users?page=1&...
        next:
          type: string
          description: Next page url
          example: https://heyteam/api/users?page=3&...
    inline_response_200_meta:
      type: object
      properties:
        current_page:
          type: integer
          description: Current page number in the pagination
          example: 2
        from:
          type: integer
          description: Number of the first user in the query result
          example: 21
        last_page:
          type: integer
          description: Last page number in the pagination
          example: 4
        path:
          type: string
          description: Endpoint url
          example: https://heyteam/api/users
        per_page:
          type: integer
          description: Number of users per page
          example: 20
        to:
          type: integer
          description: Number of last user in the query result
          example: 40
        total:
          type: integer
          description: Total number of users
          example: 128
    inline_response_201_1_data:
      type: object
      properties:
        id:
          type: integer
        client_user_id:
          type: integer
    inline_response_409_data_failed:
      type: object
      properties:
        client_user_id:
          type: integer
    inline_response_409_data:
      type: object
      properties:
        created:
          type: array
          example:
          - id: 10
            client_user_id: 20
          - id: 21
            client_user_id: 31
          items:
            $ref: '#/components/schemas/inline_response_201_1_data'
        failed:
          type: array
          example:
          - client_user_id: 20
          - client_user_id: 31
          items:
            $ref: '#/components/schemas/inline_response_409_data_failed'
        unprocessed:
          type: array
          example:
          - client_user_id: 20
          - client_user_id: 31
          items:
            $ref: '#/components/schemas/inline_response_409_data_failed'
    inline_response_200_2_original_query:
      type: object
      properties:
        client_user_id:
          type: string
          example: "123"
        id:
          type: string
          example: "321"
        professional_email:
          type: string
          example: john.doe@example.com
        name:
          type: string
          example: John Doe
    inline_response_200_2_data:
      type: object
      properties:
        id:
          type: integer
          example: 322
        name:
          type: string
          example: Requirement 1
        value:
          type: string
          example: Value 1
        type:
          type: string
          enum:
          - text
          - file
    inline_response_200_2_links:
      type: object
      properties:
        first:
          type: string
          description: First page url
          example: https://heyteam/api/requirements?page=1&...
        last:
          type: string
          description: Last page url
          example: https://heyteam/api/requirements?page=4&...
        prev:
          type: string
          description: Previous page url
          example: https://heyteam/api/requirements?page=1&...
        next:
          type: string
          description: Next page url
          example: https://heyteam/api/requirements?page=3&...
    inline_response_200_2_meta:
      type: object
      properties:
        current_page:
          type: integer
          description: Current page number in the pagination
          example: 2
        from:
          type: integer
          description: Number of the first requirement in the query result
          example: 21
        last_page:
          type: integer
          description: Last page number in the pagination
          example: 4
        path:
          type: string
          description: Endpoint url
          example: https://heyteam/api/requirements
        per_page:
          type: integer
          description: Number of requirements per page
          example: 20
        to:
          type: integer
          description: Number of last requirement in the query result
          example: 40
        total:
          type: integer
          description: Total number of requirements
          example: 128
  headers:
    X-RateLimit-Remaining:
      style: simple
      explode: false
      schema:
        type: integer
        description: The number of requests left for the 15 minute window
        format: int32
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-API-KEY
      in: header
